### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by getsecnow** [1N3/PRISM-AP#1]
i just want to say thank you for this awesome tool man. i love your work.  ok back to my question i wanted to know if for instance my wifi adapter is connected to an ap and i run prism to create the fake evil ap will the victims who connect be able to have an internet connection? and also if i have 2 wifi adapters can i use one to connect to an ap with internet access and use the other for the fake ap... my reason being that i want to create a fake ap that when victims connect to they can still get internet access when i harvest their creds and data

**Comment by 1N3** [comment]
Hey, thanks for the feedback! Appreciate that. 

In regards to your question, I haven't actually tested PRISM-AP in this configuration yet, so I'm not 100% sure if this will work or not. That being said, I don't see why it shouldn't as long as the configurations are changed to reflect the correct device (ie. eth0 -> wlan0) for your active interface. This project is still in the early "beta" phase of development, so making these changes for now must be done manually.

**Comment by getsecnow** [comment]
thanks
