### ISSUE TITLE
Prism-Ap start error

### ISSUE THREAD

**Issue by jepunband** [1N3/PRISM-AP#4]
Hi getting some errors like below:

rc = -1
pcap_read_ex(): The interface went down
Current MAC:   0e:e0:4f:8e:b8:7c (unknown)
Permanent MAC: 8c:c7:0d:32:22:4c (Liteon Technology Corporation)
New MAC:       4e:11:17:74:4f:6c (unknown)
tar: Removing leading `/' from member names
tar: /logs: Cannot stat: No such file or directory
tar (child): /bak/logs-1557393822.bak.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
 Do you want to start Evil AP?
 ===============================================================================

**Comment by 1N3** [comment]
Believe these are all "normal" errors if you're running prism-ap for the first time. I suppose I could hide these errors but in any event, it should not effect functionality if everything else is setup properly.

**Comment by jepunband** [comment]
> Believe these are all "normal" errors if you're running prism-ap for the first time. I suppose I could hide these errors but in any event, it should not effect functionality if everything else is setup properly.

the error shows up every time i run prism-ap.

**Comment by 1N3** [comment]
Looks like there was a missing variable in the script which was causing the issue. Try re-cloning the repo and re-running to see if that helps. Be sure to run the ./install.sh to install to /usr/share/prism-ap/.
